[package]
name = "zyros-nlu"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
regex = "1"
serde = { workspace = true }
serde_json = { workspace = true }
zyros-llm = { path = "../zyros-llm" }
zyros-planner = { path = "../zyros-planner" }
zyros-commands = { path = "../zyros-commands" }
